language: ruby
before_install:
  - gem install bundler
before_script:
  - appraisal install
script:
  - bundle exec appraisal rspec
gemfiles:
  - faraday_0.10.gemfile
  - faraday_0.11.gemfile
  - faraday_0.12.gemfile
  - faraday_0.13.gemfile
  - faraday_0.15.gemfile
  - faraday_0.14.gemfile
  - rails_4.2.gemfile
  - rails_5.0.gemfile
  - rails_5.1.gemfile
  - rails_5.2.gemfile
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
