version: 2.1

x-shared: &x-shared
  docker:
    - image: circleci/ruby:2.6.3-stretch-node

jobs:
  build:
    <<: *x-shared
    steps:
      - checkout
      - run:
          name: Build
          command: ./script/cibuild
      - persist_to_workspace:
          root: .
          paths: .
  publish-gem:
    <<: *x-shared
    steps:
      - attach_workspace:
          at: ~/project # circleci default working directory
      - run:
          name: Publish Gem
          command: ./script/publish_gem
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
      - publish-gem:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
